### ISSUE TITLE
Node error - Fails to launch 1.9 stable

### ISSUE THREAD

**Issue by ghost** [Furglitch/modorganizer2-linux-installer#17]
The Mod manager exits and fails to launch, oddly it works during the installation but if you close it and it completes the installation it will fail when launching from lutris.

**Comment by Desulate** [comment]
net.js:314
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:314:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (electron/js2c/browser_init.js:5669:13)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5824:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

**Comment by rockerbacon** [comment]
The information I could gather is that there is a [problem between Microsoft's WSL1 and an Electron update](https://github.com/microsoft/vscode-remote-release/issues/1420). Please make sure you're using a supported version of Vortex and Wine:

1. Open Vortex > click on the tree dots in the upper-right corner > About. Vortex version should be no greater than 1.1.15 and Node version should be 10.11.0

2. Right click on Vortex from inside Lutris > Configure > Runner Options, Wine version should be set to `lutris-5.2-x86_64`

Ensuring no.1 should be enough in your case. If the Node version is at least 12.4.0 that is assured to be the problem.

**Comment by rockerbacon** [comment]
The issue was caused by a change in behaviour in the update prompt. Before, Vortex would not install updates if the user ignored them, now it will only delay updates if the user ignores them.

Please, check the updated README with instructions on how to recover your installation and keep Vortex from updating again. I've also updated the installer to include the necessary instructions (and included some other fixes as well).

From my testing it seems it will not be possible to update Vortex before Wine releases an update to fix the issue.

Notify me as soon as your problem is resolved so I can close the issue.

**Comment by ForgetfulWasAria** [comment]
I was having this problem on Manjaro and reverting to 1.1.15 and lutris-5.2 seems to have solved it. Thank you for the quick fix.

**Comment by Desulate** [comment]
OS arch linux
Wine 5.6-1
Wine mono 5.0.0-1
Wine gecko 2.47.1-1
Winetricks 20200412-1
Lutris skyrimse installers Ver: 1.9.2 Stable
Vortex Ver: 1.1.15
Node Ver: 10.11.0
Electron Ver 4.2.12
Lutris Wine runner: lutris-5.2-x86_64
Vortex updates: disabled

[Complete installation output](https://carbon.now.sh/czs7HPK8vkr87ELsx42P)

Still the same [error output](https://carbon.now.sh/oOTDxqJWaWnPooStP9et) when I try to launch it from lutris. So I'm not sure whats going on...

Thank you for responding so quickly.

**Comment by rockerbacon** [comment]
I'm 99% sure this problem is caused by Vortex updating because I can consistently reproduce and revert the bug. If you had the problem again it's probably because Vortex had already downloaded and scheduled an update by the time you disabled them.

If updates are coming in too fast, disconnect from the internet when you get the message informing about disabling updates and reconnect after updates have been disabled in Vortex.

**Comment by Desulate** [comment]
Yes that worked! Disabling my connection at your warning prompt allowed it to install properly preventing the updates applying before its possible to prevent them.

Thank you very much for helping me with this issue.

**Comment by monyarm** [comment]
I've found a fix to this (i'm succesfully running the latest version of Vortex through Wine).
You need to run it from a terminal, so just enable CLI mode in System options.
