### ISSUE TITLE
[Bug]: MO2 for Enderal SE fails to launch

### ISSUE THREAD

**Issue by OrangeDuckNTL** [Furglitch/modorganizer2-linux-installer#805]
### Description

I tried installing MO2 for Enderal SE. I got it working for Skyrim SE, but after "succesfully installing" MO2 for Enderal SE, it fails to launch MO2 through Steam, but says it is running. As Enderal SE and Skyrim SE are rather similar, is there any chance that you could include Enderal SE? Thanks!

Install with Proton 9.0.6
[install.log](https://github.com/user-attachments/files/21530644/install.log)

Install with Proton Experimental
[install.log](https://github.com/user-attachments/files/21530806/install.log)

### Is this feature related to an issue?

- [ ] Yes
- [ ] No

**Comment by Furglitch** [comment]
Enderal SE is supported, you chose it while using the installer.

Looking through the logs, nothing seems to have failed, but I did notice I hadn't added the proton dependencies from SSE over to ESE. That's been fixed in f9ffafb and is included in 5.2.5, give that a shot and let me know if it works for you.

If it doesn't, could you include the `mo_interface.log` file in your next message? That should give me more insight into what's happening here. It'll be located in the `logs` folder within your MO2 instance. (`/home/user/Games/mod-organizer-2-enderalspecialedition/modorganizer2`, or wherever you install it on the next run.)

**Comment by Furglitch** [comment]
Just to check, what distro are you using? Are you on a Steam Deck?

**Comment by OrangeDuckNTL** [comment]
Right, forgot, I'm on Linux Mint 22.  I just checked. MO2 launched, just didn't quite launch SKSE, however, that one could be one me, as I said yes to automatic install of the script extender, as Enderal already ships its own. I'm currently re-installing to be sure I got everything clean, and then I'll get back to you :)

**Comment by Furglitch** [comment]
I wasn't aware Enderal ships with SKSE. I'll remove that from the gamesinfo.

**Comment by OrangeDuckNTL** [comment]
Hmm... still doesn't work... I've deleted all files from the Enderal folder in the Steam common folder, let it start up all the way to the Enderal start screen, then exited. Made a new prefix without a script extender, let it install MO2 with all addons, run it without mods, and upon pressing run with the SKSE launcher, its shows a black fullscreen, and crashes after 2 seconds. This is the pathway: 

Z:\home\user\Games\SteamLibrary\steamapps\common\Enderal Special Edition\skse64_loader.exe

I'm not sure what goes wrong I'm afraid... If there's anything you'd like me to do, just ask. If you have Skyrim SE, perhaps you can test it for yourself if you have time, as Enderal is free on Steam.

Also, I get this error from an installed addon:

<img width="710" height="330" alt="Image" src="https://github.com/user-attachments/assets/20234c47-d7b4-4490-a009-fd71b6920cb1" />

**Comment by OrangeDuckNTL** [comment]
I've tried with Proton Experimental and Proton 9.0.4, both with automatic script installer and no additional MO2 addons or mods, still nothing

Edit: Did some additional testing, Skyrim SE works as intended. What is interesting is that MO2 automatically finds a instance for Skyrim SE, but not for Enderal SE

**Comment by Furglitch** [comment]
Hm.. yeah, it looks like that plugin requires PyQT, which I don't believe is prepackaged with Mod Organizer nor is it something I can add simply. Unfortunately, that plugin will have to be removed until I can figure out a way to send those dependencies.

As for the black screen bug, I'm unfortunately not able to reproduce... Proton 9.0.4, no script extender install, no plugins, no mods. Got right into the main menu and started a new game. I would validate your game files and try again.

Edit: Just to double check, you are using the 5.2.5 version, correct?

**Comment by OrangeDuckNTL** [comment]
So weird... And yes, I'm using the 5.2.5, otherwise, I couldn't even get into the MO2 screen.

Must've done validating game files tons of times by now... I'll try once more.....

Edit: Sadly didn't work... Could it be that I use Linux Mint, or a dependency issue? Or perhaps the protontricks that I use, as I use com.github.Matoking.protontricks

**Comment by Furglitch** [comment]
I'm sorry, but being unable to reproduce with a totally fresh install of Enderal SE (I just added it to my Steam before testing in that last message), I'm afraid I'm not going to be much help..

It could be a distro issue, or protontricks being installed via flatpak. I can't say for sure. Maybe try installing protontricks via pipx?

Closing this as I can't repro, but if I come up with any ideas, I will let you know.

**Comment by OrangeDuckNTL** [comment]
I finally got it to work!! It may have been a case of 'have you tried turning it off-n-on again?'. I completely reinstalled Enderal, downloaded your 5.2.6 release, installed pipx, restarted, but failed to complete installing MO2, so I uninstalled pipx protontricks, installed flatpack protontricks, gave it all the rights it could ever desire with flatseal, and it works. Even after taking away rights in flatseal, it remains working. Thank you for your cooperation! <3

Edit: Okay, well... after some further testing, is DOES launch, but mods still don't work... It does load the SKSE64, esp's are in the right order (and selected)... So I'm not sure what goes wrong... I've had the same issue before, where I would run the Enderal Launcher and launch the game that way, but when I returned to SKSE, it did launch, but without the mods working.

**Comment by Furglitch** [comment]
Glad you got it (mostly) working! Though it seems your issues are more related now to MO2 itself than the installer. I've.. never played Enderal so I unfortunately won't be of any help there 😅

**Comment by OrangeDuckNTL** [comment]
You're probably right. Seems I installed the 1.6.x mods, and not the 1.5.x mods, as Enderal is a little older now. Rookie mistake ;P

Edit: IT WORKS! Thank you <3
